### ISSUE TITLE
增加筛选DML类型的参数

### ISSUE THREAD

**Issue by blackghost-01** [danfengcao/binlog2sql#10]
在实际应用中，可能只关注某一类型的操作，比如INSERT/DELETE/UPDATE，增加类型参数，便于筛选

**Comment by blackghost-01** [comment]
实际使用时，UPDATE的回滚时最麻烦的。在生成UPDATE类型的flashback SQL时，最好能再增加参数，控制哪些字段控制出现在UPDATE的SET部分，哪些字段WHERE部分，更方便的根据实际情况生成有用的回滚SQL。这里的考略因素可能比较多，比如没有主键或者唯一索引就不允许这么筛选，主键或者唯一索引中的字段是否必须出现在WHERE部分等

**Comment by danfengcao** [comment]
类型筛选确实很有必要，这个需求我后面会加上。第二个需求需要再考虑下，update的回滚sql，where部分全列出来是出于安全考虑，不会误更新，哪怕没有唯一键也不会误更新，set部分列出来是出于代码写起来方便。非常棒的问题，多谢支持，欢迎继续提问题提pull request哈

**Comment by blackghost-01** [comment]
赞，期待更多feature

**Comment by danfengcao** [comment]
按DML类型筛选的功能已加入，见 #23
