### ISSUE TITLE
用起来都是泪

### ISSUE THREAD

**Issue by zhangyupy** [danfengcao/binlog2sql#101]
为啥我 用的时候要改很多代码？不然就会报错
例如：
`with self.connection as cursor`
后面只要是用with管理的上下文都会报错，

**Comment by danfengcao** [comment]
python2.7+

章鱼 ***@***.***> 於 2022年6月24日 週五 上午9:55寫道：

**Comment by dazer007** [comment]
我也报：`with self.connection as cursor`错误

**Comment by dazer007** [comment]
确实升级版本到2.7+好了，希望能写到readme里面
