### ISSUE TITLE
请教2个问题

### ISSUE THREAD

**Issue by 364137920** [danfengcao/binlog2sql#14]
非常感谢这个软件，点赞

想要提问几个问题

1.如果是mysql5.5.9，解析执行SQL是没有问题的，但--flaskback好像不能反向解析出来，这是版本问题对吗？

2.我有一个18G的binlog文件，有没有办法做到离线分析呢？毕竟不想消耗主库的资源

**Comment by danfengcao** [comment]
1. 能给出详细过程吗？

2. 离线分析用mysqlbinlog。18个G太大了，改下max_binlog_size调成1G

**Comment by danfengcao** [comment]
这个issue先关了，有问题可以新开一个
