### ISSUE TITLE
实际测试时，无法按照db和table进行过滤，加上-B选项则可以。有遇到类似情况的吗？

### ISSUE THREAD

**Issue by bubong** [danfengcao/binlog2sql#17]
实际测试时，无法按照db和table进行过滤，加上-B选项则可以。有遇到类似情况的吗？

**Comment by danfengcao** [comment]
你好，能贴下输出结果吗？
如果是DDL语句，正向解析不会过滤，flashback模式会忽略DDL

**Comment by long904** [comment]
请问「正向解析」怎么理解？我也遇到这个问题，-d -t 过滤不了。python 版本为2.6.6，执行以下
python binlog2sql/binlog2sql/binlog2sql.py -dtest -t1129 -h127.0.0.1 -P3306 -uback -p'xxxx'  --start-file='mysql-bin.000396' 
不是我想过滤的目标库和表，解析结果是把'mysql-bin.000396'里面的内容全部解析出来了。

**Comment by long904** [comment]
刚做了个测试。通过 source xxx.sql ，-B 过滤解析出来的怎么全是 delete 语句，不应该是 insert 吗？

**Comment by danfengcao** [comment]
为避免之前db过滤包含ddl的困惑，我做了些改动。新加一个控制参数，--only-dml 用于控制解析SQL类型，默认只解析dml，现在db过滤不会再有ddl干扰。详见 #23 或最新文档

**Comment by danfengcao** [comment]
@long904 导入数据后，直接解析出来是insert语句，-B是闪回模式，生成的是回滚语句，所以生成delete是对的
