### ISSUE TITLE
python

### ISSUE THREAD

**Issue by yangql** [danfengcao/binlog2sql#18]
hi，你好
现在 binlog2sql.py 里面的 python路径是写死的 ，我们当前的机器上保留了 2.6  2.7版本的python，默认是寻找2.6版本的，但是根据 requirements.txt 安装软件时，会安装到 2.7版本下面，/usr/bin/python 默认去找 2.6 。
对于机器上有多个版本的情况 是否可以修改
#!/usr/bin/python
为
#!/usr/bin/env python
这样可以适配更多的环境类型

**Comment by danfengcao** [comment]
已改用env寻找python解释器，感谢你的建议~
