### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by imzcy1987** [danfengcao/binlog2sql#2]
elif type(binlogevent) in (WriteRowsEvent, UpdateRowsEvent, DeleteRowsEvent):
    for row in binlogevent.rows:
mysql有没有用到定制版呢？
这里获取的binlogevent.rows怎么是空呢？
{'_RowsEvent__only_schemas': None,
 '_RowsEvent__only_tables': None,
 '_RowsEvent__rows': [],
 '_ctl_connection': <pymysql.connections.Connection object at 0x7fb0fcfa87d0>,
 '_fail_on_table_metadata_unavailable': False,
 '_processed': True,
 'columns': [],
 'columns_present_bitmap': '\xff',
 'columns_present_bitmap2': '\xff',
 'complete': False,
 'event_size': 28,
 'event_type': 31,
 'extra_data': '',
 'extra_data_length': 2,
 'flags': 1,
 'number_of_columns': 2,
 'packet': <pymysqlreplication.packet.BinLogPacketWrapper object at 0x7fb0fcfa8f10>,
 'primary_key': '',
 'schema': u'zcy',
 'table': u'tb1',
 'table_id': 71,
 'table_map': {71: <pymysqlreplication.table.Table object at 0x7fb0fcfa8e90>},
 'timestamp': 1481685929}

**Comment by danfengcao** [comment]
mysql分支没有限制。加我微信，详细分析原因danfeng053005，请注明binlog2sql

**Comment by danfengcao** [comment]
perconal跟社区版都没问题。加我微信danfeng053005，详细分析原因，请注明binlog2sql

**Comment by danfengcao** [comment]
这和所用到的包python-mysql-replication的[issue #172]( https://github.com/noplay/python-mysql-replication/issues/172) 是同一个问题，imzcy1987(百度工程师)跟我一起做了调试，imzcy1987最终给出了问题答案(user需要有select权限查询元信息表，所以user需要的最小权限如下：GRANT SELECT, SUPER, REPLICATION SLAVE ON *.* TO 'test'@...)。感谢imzcy1987

**Comment by danfengcao** [comment]
@

**Comment by danfengcao** [comment]
这和所用到的包python-mysql-replication的issue #172 是同一个问题，@imzcy1987 (百度工程师)跟我一起做了调试，imzcy1987最终给出了问题答案(user需要有select权限查询元信息表，所以user需要的最小权限如下：GRANT SELECT, SUPER, REPLICATION SLAVE ON . TO 'test'@...)。感谢@imzcy1987

**Comment by danfengcao** [comment]
加个链接python-mysql-replication的[issue #172](https://github.com/noplay/python-mysql-replication/issues/172)
