### ISSUE TITLE
工具依赖的模块版本号大于指定版本行不行？

### ISSUE THREAD

**Issue by xtay573269555** [danfengcao/binlog2sql#37]
工具很好用，谢谢大神！

我看 requirements.txt  中的模块版本号用的是 “==”，请教下如果这些模块的版本号大于 requirements.txt  中指定的版本，工具是否可以正常使用？
这3个模板都已经有新版本了

PyMySQL==0.7.11
wheel==0.29.0
mysql-replication==0.13

**Comment by danfengcao** [comment]
这几个包接口新版本接口应该都没变，可以直接用的
