### ISSUE TITLE
ValueError: parameter error: start_file /data1/data/mysql/binlog.000011 not in mysql server

### ISSUE THREAD

**Issue by 15257703071** [danfengcao/binlog2sql#89]
![image](https://user-images.githubusercontent.com/22284499/135380091-d9c873d9-70d7-4366-8555-d0270ff5c0e0.png)

sudo python /root/binlog2sql-master/binlog2sql/binlog2sql.py -h192.168.5.96 -P33062 -ubinlog -pbinlogmysql001 -dfund_provider -t ShangChengOperationRecord --start-file='/data1/data/mysql/binlog.000011'

![image](https://user-images.githubusercontent.com/22284499/135380235-3cd9b63e-7ea2-40f0-8314-fe923b1e4161.png)
这是我执行的命令最终报的错，请问怎么解决这个问题？？

**Comment by Zhangdeli1993** [comment]
我也是这个问题,请问后来怎么解决了

**Comment by yyu0378** [comment]
start-file这个参数是程序从mysql服务读取的，不用指定路径，仅指定名字即可

**Comment by Zhangdeli1993** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "danfengcao/binlog2sql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 下午4:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [danfengcao/binlog2sql] ValueError: parameter error: start_file /data1/data/mysql/binlog.000011 not in mysql server (#89)





 
start-file这个参数是程序从mysql服务读取的，不用指定路径，仅指定名字即可
