### ISSUE TITLE
如果有外健关联的情况下不能删除

### ISSUE THREAD

**Issue by pulord** [danfengcao/binlog2sql#9]
(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`*`.`*`, CONSTRAINT `key_wp_agent` FOREIGN KEY (`*`) REFERENCES `*` (`*`) ON DELETE NO ACTION ON UPDATE CASCADE)')

**Comment by pulord** [comment]
SET FOREIGN_KEY_CHECKS=0
SET FOREIGN_KEY_CHECKS=1
http://stackoverflow.com/questions/9912663/mysql-delete-a-row-ignoring-foreign-key-constraint

**Comment by pulord** [comment]
如果遇到1406, "Data too long for column 'active' at row 1"，可以看一下是否是sql字段是否是bit 
以下处理即可
def fix_object(value):
    """Fixes python objects so that they can be properly inserted into SQL queries"""
    str_v = ""
    if isinstance(value, unicode):
        str_v = value.encode('utf-8')
    else:
        str_v = value
    try:
        return int(str_v)
    except Exception as e:
        return str_v

**Comment by danfengcao** [comment]
你好，能详细复现下吗？我觉得这个问题不错，值得再探究

**Comment by pulord** [comment]
我有两个table A B
插入a数据的时候会插入b一条数据
a的某个字段是外健，引用了b的id
用binlog2sql解析出来的sql
是先删除b数据，然后删除a，在删除a的时候报1451, 'Cannot delete or update a parent row: a foreign key constraint fails）

当前我是通过强制关闭外健的检查的功能来跳过这个，期望可以解决此问题
