### ISSUE TITLE
[设计讨论]脚本需要连接服务器的原因？

### ISSUE THREAD

**Issue by EverSpring** [danfengcao/binlog2sql#95]
您好，感谢提供的脚本
**有个问题想了解一下，为什么您在设计的时候需要连接到服务器呢？**
从代码层面初步了解到，从库中查了SHOW MASTER STATUS、server_id等信息，但连接到数据库后会受到mysql server配置影响，比如max_allowed_packet（max_allowed_packet一般情况下是默认值），我们的应用场景大多是恢复生产数据，如果要恢复还需要修改服务器参数等，对生产影响较大，谢谢！

**Comment by feixfly** [comment]
我也好奇..为啥要连接数据库..直接用mysqlbinlog导出整理嘛

**Comment by michael-liumh** [comment]
获取表的元数据，字段类型、字段顺序等

**Comment by wxtt522** [comment]
读取离线文件也能获取表结构啊

**Comment by michael-liumh** [comment]
那为啥作者不读取离线文件，反而要连接实际呢？就是因为无法从离线文件中获取表结构呀，binlog里面存的是库编号、表编号、列编号来的，这个编号要进行转换，所以才要连接实际



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月31日(周三) 中午11:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [danfengcao/binlog2sql] [设计讨论]脚本需要连接服务器的原因？ (Issue #95)




 
读取离线文件也能获取表结构啊

**Comment by huangwei2013** [comment]
> 我也好奇..为啥要连接数据库..直接用mysqlbinlog导出整理嘛

@gxlffly  按这个做法，你也不需要这个项目，直接用 mysqlbinlog 咯。。。。

**Comment by AndyLue** [comment]
同感，让我们加上这个需求吧
